# Generated by Django 5.2.6 on 2025-09-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duedate',
        ),
    ]
