# Generated by Django 5.2.6 on 2025-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
