# Generated by Django 5.2.6 on 2025-09-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='column',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='blank', max_length=50),
        ),
    ]
