# Generated by Django 5.2.6 on 2025-09-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='column',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
