# Generated by Django 5.2.6 on 2025-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='column',
            field=models.CharField(max_length=20),
        ),
    ]
