# Generated by Django 5.2.6 on 2025-09-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='column',
        ),
    ]
